import psycopg

DB_CONFIG = {
    "host": "localhost",
    "port": 5432,
    "dbname": "attendai",
    "user": "postgres",
    "password": "postgres"
}

schema = """
-- Teachers
CREATE TABLE IF NOT EXISTS teachers (
    teacher_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    name TEXT
);

-- Students
CREATE TABLE IF NOT EXISTS students (
    student_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    face_embedding JSONB,
    voice_embedding JSONB
);

-- Subjects
CREATE TABLE IF NOT EXISTS subjects (
    subject_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_code TEXT NOT NULL UNIQUE,
    name TEXT DEFAULT 'UNKNOWN',
    section TEXT DEFAULT 'N/A',
    teacher_id BIGINT,
    CONSTRAINT fk_teacher
        FOREIGN KEY (teacher_id)
        REFERENCES teachers(teacher_id)
        ON DELETE SET NULL
);

-- Subject Students (Many-to-Many)
CREATE TABLE IF NOT EXISTS subject_students (
    subject_id BIGINT,
    student_id BIGINT,

    PRIMARY KEY (subject_id, student_id),

    CONSTRAINT fk_subject
        FOREIGN KEY (subject_id)
        REFERENCES subjects(subject_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_student
        FOREIGN KEY (student_id)
        REFERENCES students(student_id)
        ON DELETE CASCADE
);

-- Attendance Logs
CREATE TABLE IF NOT EXISTS attendance_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    "timestamp" TIMESTAMPTZ DEFAULT NOW(),

    subject_id BIGINT,
    student_id BIGINT,

    is_present BOOLEAN DEFAULT TRUE,

    CONSTRAINT fk_attendance_subject
        FOREIGN KEY (subject_id)
        REFERENCES subjects(subject_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_attendance_student
        FOREIGN KEY (student_id)
        REFERENCES students(student_id)
        ON DELETE CASCADE
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_attendance_student
ON attendance_logs(student_id);

CREATE INDEX IF NOT EXISTS idx_attendance_subject
ON attendance_logs(subject_id);

CREATE INDEX IF NOT EXISTS idx_subject_teacher
ON subjects(teacher_id);
"""

def create_database():
    try:
        with psycopg.connect(**DB_CONFIG) as conn:
            with conn.cursor() as cur:
                cur.execute(schema)
            conn.commit()

        print("Database schema created successfully!")

    except Exception as e:
        print("Error:", e)


if __name__ == "__main__":
    create_database()